name: flutter_crypto
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  walletconnect_qrcode_modal_dart: ^0.0.5
  web3dart: ^2.3.5
  build_runner: ^2.1.2
  web_socket_channel: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
